### ISSUE TITLE
Deleting amount from local currency box does not clear my currency boxes

### ISSUE THREAD

**Issue by andreacrain** [freakboy3742/traveltips#1]
To reproduce, type 15 in the local currency box. Then delete the 5, and see that the my currency boxes change to display the amounts appropriate for a local currency value of 1, as they should since 1 is all that remains in the local currency box. Then delete the from the local currency box 1, and notice that the my currency boxes still display the amounts for the value of 1. They should be cleared instead.

**Comment by freakboy3742** [comment]
Confirmed; Thanks for the report!

**Comment by freakboy3742** [comment]
Looks like this has now been fixed.
